openapi: 3.0.3
info:
  title: TaskFlow API
  description: API for project management with full CRUD on Projects and Tasks.
  version: 1.2.0
servers:
  - url: https://api.taskflow.com/v1
    description: Production Server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Resource not found
    Project:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: "a1b2c3d4-e5f6-7890-1234-56789abcdef0"
        name:
          type: string
          example: "Website Redesign"
        description:
          type: string
          example: "Q4 Marketing website overhaul"
    Task:
      type: object
      required:
        - id
        - title
        - status
        - projectId
      properties:
        id:
          type: string
          format: uuid
          example: "f1e2d3c4-b5a6-0987-6543-21098fedcba0"
        title:
          type: string
          example: "Fix Navbar Responsiveness"
        status:
          type: string
          enum: [TODO, IN_PROGRESS, REVIEW, DONE]
          example: "IN_PROGRESS"
        projectId:
          type: string
          format: uuid
          example: "a1b2c3d4-e5f6-7890-1234-56789abcdef0"
security:
  - bearerAuth: []
paths:
  /projects:
    get:
      summary: List Projects
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      summary: Create Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: "New Mobile App"
                description:
                  type: string
                  example: "iOS and Android MVP"
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /projects/{projectId}:
    get:
      summary: Get Project Details
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update Project
      description: Update project name or description.
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Project Name"
                description:
                  type: string
                  example: "Updated description"
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete Project
      description: Remove a project and its associated tasks.
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Project deleted successfully
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /projects/{projectId}/tasks:
    post:
      summary: Create Task inside Project
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  example: "Implement Login"
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
